hatimeria_ext_js:
  signin_route: fos_user_security_login
  javascript_mode:  ext-all-dev
  compiled: false
  locales: ["pl"]
  mappings:
    Hatimeria\Bundle\CMFBundle\Entity\User:
      fields:
        default: [id, username, email]
    Hatimeria\Bundle\CMFBundle\Entity\CmsPage:
      fields:
        default: [id, title, path, body, author, publish_from, publish_to, created_at, is_published, meta_description, meta_keywords]