HatimeriaAdminBundle:
    resource: "@HatimeriaAdminBundle/Resources/config/routing.xml"
    
HatimeriaExtJSBundleDirect:
    resource: "@HatimeriaExtJSBundle/Resources/config/routing/direct.yml"    
    
HatimeriaExtJSBundleSecurity:
    resource: "@HatimeriaExtJSBundle/Resources/config/routing/security.yml"

homepage:
    pattern: /
    defaults: { _controller: HatimeriaAdminBundle:Admin:index}
    
    
test:
    pattern: /test
    defaults: { _controller: HatimeriaAdminBundle:Test:index}

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
_bazinga_exposetranslation:
    resource: "@BazingaExposeTranslationBundle/Resources/config/routing/routing.yml"    