security:
    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        main:
            # todo access denied page
            pattern: ^/
            switch_user: {role: ROLE_ADMIN}
            form_login:
                provider: fos_userbundle
                always_use_default_target_path: true
                default_target_path: /after-login  
            logout:       true
            anonymous:    true
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
